# Generated by Django 4.2 on 2023-04-18 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_author_course'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='course',
            new_name='Courses',
        ),
    ]
