# Generated by Django 4.2 on 2023-04-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_course_courses'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='courses',
            name='Class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.class'),
        ),
    ]
