# Generated by Django 4.2 on 2023-04-19 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_lavel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lavel',
            name='name',
            field=models.CharField(default=None, max_length=3),
        ),
    ]
