# Generated by Django 4.2 on 2023-04-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_lavel_level_rename_lavel_courses_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.IntegerField(),
        ),
    ]
