# Generated by Django 4.2 on 2023-04-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
