# Generated by Django 4.2 on 2023-04-19 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='level',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.level'),
        ),
    ]
