# Generated by Django 4.2 on 2023-04-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_level_slug_alter_courses_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=500)),
                ('phone', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('portal_name', models.CharField(max_length=100)),
            ],
        ),
    ]
