# Generated by Django 4.2 on 2023-05-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_institute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='level',
            name='slug',
        ),
    ]
