# Generated by Django 4.2 on 2023-05-03 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_author_author_profile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='learning_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='requirement_point',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='author_profile',
            field=models.ImageField(upload_to='media/author'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='featured_image',
            field=models.ImageField(null=True, upload_to='media/featured_img'),
        ),
    ]
