# Generated by Django 4.2 on 2023-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_author_author_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='language',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
