# Generated by Django 4.2 on 2023-05-03 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_courses_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='certificate',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], max_length=100, null=True),
        ),
    ]
