# Generated by Django 4.2 on 2023-05-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_alter_courses_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='certificate',
            field=models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=100, null=True),
        ),
    ]
