# Generated by Django 4.2 on 2023-05-05 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_lessons_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='description',
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
