# Generated by Django 4.2 on 2023-05-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_remove_lessons_description_video_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='time_duration',
            field=models.CharField(max_length=10),
        ),
    ]
