# Generated by Django 4.2 on 2023-05-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0039_news_notices_partners_testimonials_upcoming_events_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='sub_text',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
