# Generated by Django 4.2 on 2023-05-08 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_institute_sub_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(default=None, null=True, upload_to='media/institute/logos'),
        ),
    ]
