# Generated by Django 4.2 on 2023-05-08 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_alter_institute_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='logo',
            field=models.ImageField(blank=True, default=None, upload_to='media/institute/logos'),
        ),
    ]
