# Generated by Django 4.2 on 2023-05-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_institute_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='testi_photo',
            field=models.ImageField(default=None, upload_to='media/testimonials'),
        ),
    ]
